const Images = {
  nutrak_logo: require('./nutrak-logo.png'),
  streak: require('./streak.png'),
  scan: require("./scan.png"),
  streak_active: require("./streak-active.png"),
  streak_bg: require("./streak-bg.png"),
  silver_medal: require("./Silver.png"),
  bronze_medal: require("./Bronze.png"),
  gold_medal: require("./Gold.png"),
  platinum_medal: require("./Platinum.png"),
  arrow_right: require("./arrowRight.png"),
  imageBanner: require("./banner.png"),
  calories: require("./calories.png"),
  calcium: require("./calcium.png"),
  carbs: require("./carbs.png"),
  fats: require("./fats.png"),
  iron: require("./iron.png"),
  proteins: require("./proteins.png"),
  scan_icon: require("./scanItem.png"),
  gallery_icon: require("./galleryIcon.png"),
  about: require("./about.png"),
  camera_icon: require("./camera-icon.png"),
};

export default Images;